# Generated by Django 4.1.7 on 2023-03-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='hospital',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('account', 'account'), ('billing', 'billing'), ('sales', 'sales'), ('custom', 'custom')], max_length=7),
        ),
    ]
