# Generated by Django 4.1.7 on 2023-03-13 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1000)),
                ('brand_name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tax_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='vendors',
            old_name='contact',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='vendors',
            name='email',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='users_role',
        ),
        migrations.AlterField(
            model_name='vendors',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_information'),
        ),
    ]
