# Generated by Django 4.1.7 on 2023-03-07 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_vendors_contact_remove_vendors_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('contact', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tax_id', models.CharField(max_length=1000)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vendors')),
            ],
        ),
    ]
