# Generated by Django 4.1.7 on 2023-03-09 04:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_company_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_information',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendors',
            name='company_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_information'),
        ),
    ]
